### ISSUE TITLE
WebApp loading animation

### ISSUE THREAD

**Issue by rsmything** [zubiden/tg-web-bot-demo#2]
Hello, can you explain please how to add an animation (gif) when webapp is loading like these apps

@DurgerKingBot
- MacOS
<img width="325" alt="Снимок экрана 2023-06-14 в 13 04 07" src="https://github.com/zubiden/tg-web-bot-demo/assets/11719983/975aaa34-ccd1-410a-959b-812f7b50ff6e">

- iOS
https://github.com/zubiden/tg-web-bot-demo/assets/11719983/639b1ed5-7a67-4207-866f-e30b6254da43

@asmico_attach_bot
- MacOS
<img width="1233" alt="Снимок экрана 2023-06-14 в 13 14 03" src="https://github.com/zubiden/tg-web-bot-demo/assets/11719983/d45e4bd8-e72c-446e-a920-34a7546ce71c">

When i start a new app it shows white blank page while telegram isn't loaded

**Comment by zubiden** [comment]
Sorry for the late response, missed my email notification. 
Those animations are hardcoded on the client side, there's no way to change them right now
