### ISSUE TITLE
playing esp8266 schedule web app

### ISSUE THREAD

**Issue by ldijkman** [zubiden/tg-web-bot-demo#3]
hello 

trying to find a way to have a schedule time input and duration web app
and have the data send to the bot 
and or esp8266

https://t.me/Luberth_Dijkman

![telegram_delete_task](https://github.com/zubiden/tg-web-bot-demo/assets/45427770/6198d424-c913-462b-8f1c-a9cb771419b7)

**Comment by zubiden** [comment]
Sorry, I can't help with that. Try asking in https://t.me/BotTalk or a similar chat
